### ISSUE TITLE
New setting to restrict the number of level 1 nodes

### ISSUE THREAD

**Issue by anchovy** [verbb/navigation#277] opened 2022-01-13 00:39 UTC
**What are you trying to do?**
Restrict the number of level 1 nodes.

**What's your proposed solution?**
Add a setting to restrict the number of level 1 nodes allowed. i.e. Max  level 1 nodes (leave blank for unlimited)

Would work similar to the existing _Max Level_ setting.

**Comment by engram-design** [comment] 2022-01-13 01:58
FYI, duplicate of https://github.com/verbb/navigation/issues/276 which also will handle sub-item limits.

**Closed as completed by engram-design** 2022-01-13 01:58 UTC
Labels: feature request

**Comment by engram-design** [comment] 2022-10-25 09:10
Added for the next release. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.
