### ISSUE TITLE
Latest version sets passive nodes to active

### ISSUE THREAD

**Issue by kkeith-adg** [verbb/navigation#240] opened 2021-01-18 16:08 UTC
**Description**
My root level passive nodes are now defaulting to active after upgrading to 1.4.12. Worked as expected in 1.4.10. This is causing them to be highlighted in my header design unnecessarily.

**Steps to reproduce**
1. Create a navigation using a passive item at the root
2. Use within a template and check nav_item.active

**Additional info**
- Plugin version: 1.4.12
- Craft version: 3.5.17.1
- Multi-site: No
- Propagate nodes: No

**Comment by engram-design** [comment] 2021-01-19 11:33
Should be fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-3 as 1.4.12",
  "...": "..."
}
```

Then run `composer update`.

**Comment by DavidKabelitz** [comment] 2021-01-25 14:56
When will be the next release?

**Comment by engram-design** [comment] 2021-01-26 01:11
Fixed in [1.4.13](https://github.com/verbb/navigation/releases/tag/1.4.13)

**Comment by DavidKabelitz** [comment] 2021-01-28 15:40
Not working for us. Still all nodes are set to active in 1.4.13. At the template we still check it with node.active right?

**Comment by DavidKabelitz** [comment] 2021-01-28 15:53
Looks like its just a problem at the root. Subpages are fine but at the front page all nodes are active

**Comment by engram-design** [comment] 2021-01-28 22:58
@DavidKabelitz You mention it's marking all your nodes as active, not just passive nodes like the OP? I'm testing on the homepage with a collection of different nodes, types and URLs without seeing them be all active.

Can you advise on the types and URLs of a few of your nodes that are marked as active when on the homepage?

**Comment by DavidKabelitz** [comment] 2021-01-29 11:40
Hi @engram-design , Single Entries without sub nodes are fine. We have sub nodes were the parent is a custom url without a link. All of them are set to active. I guess the problem is the empty url right?

**Comment by engram-design** [comment] 2021-01-29 11:52
Ah, I see. Yep, so if you have a custom URL with no URL value (blank) it's classified as the homepage. It probably _shouldn't_ but we've also had support requests specifically asking for this to be the case. Maybe I should've put my foot down a bit more 😅

So essentially a manual URL with `/` or `` is exactly the same.

I would say if you have a node with an empty URL, that you don't want to be the homepage, switch it to a passive node.

**Comment by DavidKabelitz** [comment] 2021-01-29 11:58
What does it mean "switch to a passive node", what we need to do?

**Comment by DavidKabelitz** [comment] 2021-01-29 11:59
ah ok...there is a new node type "passive" did not recognized before, my fault ;)

**Comment by DavidKabelitz** [comment] 2021-01-29 12:01
Passive node works perfect, thx

**Closed as completed** 2021-01-30 01:29 UTC
