### ISSUE TITLE
Sometimes the first node can't have children.

### ISSUE THREAD

**Issue by spAnser** [verbb/navigation#82] opened 2019-03-19 16:04 UTC
### Description
So this one is weird I can't seem to reproduce it. There also isn't any errors associated with it.

![2019-03-19 10-57-55 2019-03-19 11_00_08](https://user-images.githubusercontent.com/193938/54621706-2f136380-4a36-11e9-9508-ed5cf705e2df.gif)

It is even weirder with multiple child nodes:

![2019-03-19 11-01-43 2019-03-19 11_03_58](https://user-images.githubusercontent.com/193938/54621995-b8c33100-4a36-11e9-86be-3f9041a9845c.gif)

I couldn't replicate this creating a new navigation so maybe something from an old navigation didn't migrate properly...?

### Additional info

- Plugin version: 1.1.11
- Craft version: 3.1.18

**Comment by engram-design** [comment] 2020-08-09 12:24
Closing for now, as I can't reproduce either, and it was some time ago. Please let me know if it's continuing to be an issue.

**Closed as completed by engram-design** 2020-08-09 12:24 UTC
