### ISSUE TITLE
Editing a Custom URL nav item sets value of dropdown automatically to Entries

### ISSUE THREAD

**Issue by frontedbe** [verbb/navigation#225] opened 2020-12-03 15:46 UTC
**Description**
Editing a Custom URL nav item sets value of dropdown automatically to Entries
[view screenshot](https://share.getcloudapp.com/8LunJYJZ)

**Additional info**
- Plugin version: 1.4.5
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: Yes

**Comment by engram-design** [comment] 2020-12-06 21:02
Duplicate of https://github.com/verbb/navigation/issues/226

**Closed as completed by engram-design** 2020-12-06 21:02 UTC
