### ISSUE TITLE
Upgrade to 2.0.13 and all Nav's disappear in control panel

### ISSUE THREAD

**Issue by sunscreem** [verbb/navigation#332] opened 2022-11-28 10:57 UTC
### Describe the bug

I've just updated several sites to version 2.0.13 and the nav's are now empty.

![image](https://user-images.githubusercontent.com/7523595/204260702-59d01c44-6ca6-4226-ae2c-5bf59cb7e13b.png)

I've also got failing queued jobs:

![image](https://user-images.githubusercontent.com/7523595/204260634-efc85de1-c03f-491e-af4e-7a476e9689c1.png)

### Steps to reproduce

1.  Update to 2.0.13
2

### Craft CMS version

Craft Pro 4.3.3

### Plugin version

2.0.13

### Multi-site?

No

### Additional context

This is reproduceable on several sites I upgraded on Sunday.

**Comment by engram-design** [comment] 2022-11-30 01:47
Can you post the content of your queue job, so I can see more detail about the error? There should also be information in your `storage/logs/navigation.log` ,  `storage/logs/web.log`  or  `storage/logs/queue.log` files.

**Comment by mortendk** [comment] 2022-11-30 22:58
can confirm the same issue here after i just upgraded 
The navigations are visible though on the site but no backend - also cant apply config to the production site (auch)

```
error: The nav 'Header Navigation' is not enabled for the site '1'
2022-11-30 22:51:04 [console.ERROR] [craft\errors\UnsupportedSiteException] The nav 'Header Navigation' is not enabled for the site '1' {"trace":["#0 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2803): verbb\\navigation\\elements\\Node->beforeSave(false)","#1 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1039): craft\\services\\Elements->_saveElementInternal(Object(verbb\\navigation\\elements\\Node), true, false, NULL)","#2 /var/www/html/vendor/verbb/navigation/src/services/Nodes.php(109): craft\\services\\Elements->saveElement(Object(verbb\\navigation\\elements\\Node), true, false)","#3 [internal function]: verbb\\navigation\\services\\Nodes->onSaveElement(Object(craft\\events\\ElementEvent))","#4 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\\events\\ElementEvent))","#5 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\\base\\Event::trigger('craft\\\\services\\\\...', 'beforeSaveEleme...', Object(craft\\events\\ElementEvent))","#6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2799): yii\\base\\Component->trigger('beforeSaveEleme...', Object(craft\\events\\ElementEvent))","#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1039): craft\\services\\Elements->_saveElementInternal(Object(craft\\elements\\Entry), false, false, NULL)","#8 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(1509): craft\\services\\Elements->saveElement(Object(craft\\elements\\Entry), false)","#9 /var/www/html/vendor/craftcms/cms/src/services/Sections.php(1198): craft\\services\\Sections->_ensureSingleEntry(Object(craft\\models\\Section))","#10 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1678): craft\\services\\Sections->handleChangedEntryType(Object(craft\\events\\ConfigEvent))","#11 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1125): craft\\console\\Application->craft\\base\\{closure}(Object(craft\\events\\ConfigEvent))","#12 [internal function]: craft\\services\\ProjectConfig->handleChangeEvent(Object(craft\\events\\ConfigEvent))","#13 /var/www/html/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\\events\\ConfigEvent))","#14 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\\base\\Component->trigger('updateItem', Object(craft\\events\\ConfigEvent))","#15 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1115): craft\\models\\ProjectConfigData->commitChanges(Array, Array, 'entryTypes.216f...')","#16 [internal function]: craft\\services\\ProjectConfig->handleChangeEvent(Object(craft\\events\\ConfigEvent))","#17 /var/www/html/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Array, Object(craft\\events\\ConfigEvent))","#18 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(82): yii\\base\\Component->trigger('updateItem', Object(craft\\events\\ConfigEvent))","#19 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1231): craft\\models\\ProjectConfigData->commitChanges(Array, Array, 'entryTypes.216f...', false, NULL, true)","#20 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1244): craft\\services\\ProjectConfig->craft\\services\\{closure}('entryTypes.216f...')","#21 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(577): craft\\services\\ProjectConfig->_applyChanges(Array, Object(craft\\models\\ProjectConfigData), Object(craft\\models\\ReadOnlyProjectConfigData))","#22 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(303): craft\\services\\ProjectConfig->applyExternalChanges()","#23 [internal function]: craft\\console\\controllers\\ProjectConfigController->actionApply()","#24 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#25 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#26 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction('apply', Array)","#27 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(224): yii\\console\\Controller->runAction('apply', Array)","#28 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\\console\\Controller->runAction('apply', Array)","#29 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction('project-config/...', Array)","#30 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\\console\\Application->runAction('project-config/...', Array)","#31 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction('project-config/...', Array)","#32 /var/www/html/vendor/craftcms/cms/src/console/Application.php(121): yii\\console\\Application->handleRequest(Object(craft\\console\\Request))","#33 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\\console\\Application->handleRequest(Object(craft\\console\\Request))","#34 /var/www/html/craft(22): yii\\base\\Application->run()","#35 {main}"],"memory":38052008,"exception":"[object] (craft\\errors\\UnsupportedSiteException(code: 0): The nav 'Header Navigation' is not enabled for the site '1' at /var/www/html/vendor/verbb/navigation/src/elements/Node.php:681)"} 
2022-11-30 22:51:04 [console.WARNING] [application] Request context:

```

![CleanShot 2022-12-01 at 00 00 54](https://user-images.githubusercontent.com/65756/204926488-7e3f0dec-2be8-441f-8c02-80f93cb05e42.png)

**Comment by engram-design** [comment] 2022-12-01 00:11
@mortendk is your site a multi-site? If so, are you able to have a look at the Navigation settings and see if there's any sites enabled?

**Comment by sunscreem** [comment] 2022-12-01 10:32
@engram-design Here's the error for me in the back end:

![image](https://user-images.githubusercontent.com/7523595/205030215-d8473bff-a0a7-4691-95c1-482406bce9fb.png)

Can confirm this is not a multisite site.

Let me know if you need anything from those log files :)

**Comment by mortendk** [comment] 2022-12-01 10:41
Nope single site Lemme know if you wanna dive into the settings, so we can get to the bottom of this 

Strange thing is my local setup is working fine - but all instances on the dev, prod, live servers are having the samme issue with navigation 

![CleanShot 2022-12-01 at 11 39 22](https://user-images.githubusercontent.com/65756/205032112-289d76a3-b756-4446-a95a-e7bd0e2f1e9f.png)

**Comment by engram-design** [comment] 2022-12-01 12:40
Thanks for the info, this has cropped up a [few](https://github.com/verbb/navigation/issues/330) [times](https://github.com/verbb/navigation/issues/309) and thought I'd gotten to the bottom of it.

I've just run some Craft 3  > 4 updates with a non-multi site, but unable to reproduce this.

Would you be able to send through your `navigation_navs` database table from **before** your upgrade to Craft 4?

**Comment by mortendk** [comment] 2022-12-01 13:41
sure where should i dump it

**Comment by engram-design** [comment] 2022-12-01 19:52
Here, or send to `web at verbb.io`

**Comment by sunscreem** [comment] 2022-12-02 11:17
Hey @engram-design 

```mysql
--
-- Table structure for table `navigation_navs`
--

DROP TABLE IF EXISTS `navigation_navs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `navigation_navs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `structureId` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `handle` varchar(255) NOT NULL,
  `instructions` text,
  `sortOrder` smallint unsigned DEFAULT NULL,
  `propagateNodes` tinyint(1) DEFAULT '0',
  `maxNodes` int DEFAULT NULL,
  `permissions` text,
  `fieldLayoutId` int DEFAULT NULL,
  `defaultPlacement` enum('beginning','end') NOT NULL DEFAULT 'end',
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `dateDeleted` datetime DEFAULT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `navigation_navs_handle_idx` (`handle`),
  KEY `navigation_navs_structureId_idx` (`structureId`),
  KEY `navigation_navs_fieldLayoutId_idx` (`fieldLayoutId`),
  KEY `navigation_navs_dateDeleted_idx` (`dateDeleted`),
  CONSTRAINT `navigation_navs_fieldLayoutId_fk` FOREIGN KEY (`fieldLayoutId`) REFERENCES `fieldlayouts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `navigation_navs_structureId_fk` FOREIGN KEY (`structureId`) REFERENCES `structures` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `navigation_navs_sites`
--

DROP TABLE IF EXISTS `navigation_navs_sites`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `navigation_navs_sites` (
  `id` int NOT NULL AUTO_INCREMENT,
  `navId` int NOT NULL,
  `siteId` int NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_vedbatowakfjdkswbadcjejnppcbcixpqlfy` (`navId`,`siteId`),
  KEY `idx_tweesncvbdwrxajomfosyivzujdegxwkpqgg` (`siteId`),
  CONSTRAINT `fk_ptzcdywmypdpuzxmvthitaotlwoxyxrgstfy` FOREIGN KEY (`navId`) REFERENCES `navigation_navs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_qwtoatwdcsdfiofmsjiiiguywmpejckicjvl` FOREIGN KEY (`siteId`) REFERENCES `sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `navigation_nodes`
--

DROP TABLE IF EXISTS `navigation_nodes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `navigation_nodes` (
  `id` int NOT NULL,
  `elementId` int DEFAULT NULL,
  `navId` int NOT NULL,
  `parentId` int DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `classes` varchar(255) DEFAULT NULL,
  `urlSuffix` varchar(255) DEFAULT NULL,
  `customAttributes` text,
  `data` text,
  `newWindow` tinyint(1) DEFAULT '0',
  `deletedWithNav` tinyint(1) DEFAULT NULL,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `navigation_nodes_navId_idx` (`navId`),
  KEY `navigation_nodes_elementId_fk` (`elementId`),
  CONSTRAINT `navigation_nodes_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE SET NULL,
  CONSTRAINT `navigation_nodes_id_fk` FOREIGN KEY (`id`) REFERENCES `elements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `navigation_nodes_navId_fk` FOREIGN KEY (`navId`) REFERENCES `navigation_navs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
```

And 

```mysql

--
-- Dumping data for table `navigation_navs`
--

LOCK TABLES `navigation_navs` WRITE;
/*!40000 ALTER TABLE `navigation_navs` DISABLE KEYS */;
set autocommit=0;
INSERT INTO `navigation_navs` VALUES (1,15,'Main Navigation','mainNavigation','',1,0,NULL,'[]',NULL,'end','2020-10-06 14:19:10','2020-10-21 21:00:57',NULL,'624331e2-17de-4811-94d3-f531f0f2fe2c'),(2,16,'Footer Navigation','footerNavigation','',2,0,NULL,'[]',NULL,'end','2020-10-06 14:19:20','2020-10-21 21:00:57',NULL,'7b16b632-09ad-4bc9-9807-fe3ca97df708');
/*!40000 ALTER TABLE `navigation_navs` ENABLE KEYS */;
UNLOCK TABLES;
commit;

--
-- Dumping data for table `navigation_navs_sites`
--

LOCK TABLES `navigation_navs_sites` WRITE;
/*!40000 ALTER TABLE `navigation_navs_sites` DISABLE KEYS */;
set autocommit=0;
/*!40000 ALTER TABLE `navigation_navs_sites` ENABLE KEYS */;
UNLOCK TABLES;
commit;

--
-- Dumping data for table `navigation_nodes`
--

LOCK TABLES `navigation_nodes` WRITE;
/*!40000 ALTER TABLE `navigation_nodes` DISABLE KEYS */;
set autocommit=0;
INSERT INTO `navigation_nodes` VALUES (4081,4076,1,NULL,NULL,'craft\\elements\\Entry','','','','[]',0,NULL,'2020-10-06 14:20:28','2020-10-06 14:24:08','92adea3d-0225-42d0-851f-d31ac00e4ee9'),(4082,2545,2,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-06 14:21:29','2020-10-06 14:21:29','e55cf11f-9884-4bfe-9e70-24005c16ca2c'),(4083,3819,2,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-06 14:23:31','2020-10-06 14:23:31','9d1d822d-cca6-4d11-8391-4a62244e9e5a'),(4084,3817,2,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-06 14:23:31','2020-10-06 14:23:31','1b2a141a-3e2a-4d7b-bfcd-a940268c1eee'),(4085,3821,2,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-06 14:23:31','2022-06-18 15:52:28','9af8e206-1bad-482e-ac10-c12ada7c8dc0'),(4087,1763,1,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-06 14:23:51','2020-10-06 14:23:51','52e4d11b-9848-4ca3-8b8b-5cd86c132c8d'),(4089,2545,1,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-06 14:24:03','2022-06-18 15:52:26','0ff2fa30-7cb7-4c51-91cb-373bfd62e330'),(4217,4212,1,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-17 14:43:06','2020-10-17 14:43:06','c1c77d23-6ec7-4a87-9745-cee1005e78e9'),(4341,4332,1,NULL,NULL,'craft\\elements\\Entry',NULL,NULL,'[]','[]',0,NULL,'2020-10-24 15:26:01','2020-10-24 15:26:01','34a08916-211f-4fdd-abf4-4baa58da8aed');
/*!40000 ALTER TABLE `navigation_nodes` ENABLE KEYS */;
UNLOCK TABLES;
commit;

```

This was from craft 4.2.5.1 - I'm not 100% which version of the plug in was in use at that time.

**Comment by engram-design** [comment] 2022-12-03 03:07
Thank for that, so just to confirm - you were only updating from Craft 4.2.5.1 and some recent-ish version of Navigation? I assumed this was from an older install like Craft 3! I'm not sure if that's the same scenario for @mortendk 

The migrations _should_ be taking care of missing `navigation_navs_sites` entries already (shown by there being no items in your database table. But I've just pushed another further fix for this to hopefully have it apply.

Hopefully fixed in [2.0.14](https://github.com/verbb/navigation/releases/tag/2.0.14)

**Comment by sunscreem** [comment] 2022-12-04 18:01
Hey @engram-design I just upgraded to 2.0.14 on one of the problem sites and the navigations are still all blank I'm afraid:


![image](https://user-images.githubusercontent.com/7523595/205507487-a9f5f6e9-18e3-498a-92ad-b76fcb278788.png)

**Comment by engram-design** [comment] 2022-12-04 19:56
That doesn't make sense. The [migration](https://github.com/verbb/navigation/blob/craft-4/src/migrations/m221203_000000_fix_empty_nav_sites.php) should look at any nav rows in your `navigation_navs` db table, and if no rows are found in the `navigation_navs_sites`, it'll create them.

Can you confirm if you have rows in your `navigation_navs` and `navigation_navs_sites` tables after the update?

**Comment by mortendk** [comment] 2022-12-05 10:03
Just ran the 2.14 update and voila ! 🥇 
it works on my machine (and servers) awesome thanx @engram-design

**Comment by sunscreem** [comment] 2022-12-05 15:34
@engram-design I've just tried updating this on another site and everything seems to working fine again now! Apologies for the confusion, I guess I was doing something dumb!

**Comment by engram-design** [comment] 2022-12-05 21:47
@sunscreem Glad to hear! Just let me know if it crops up again.

**Comment by bgooren** [comment] 2023-01-05 18:26
Hi @engram-design; Sorry to ping you on this, but it's (still) not working for me...

We just upgraded to craft 4 (3.7.62 => 4.3.5, navigation 1.4.31 => 2.0.15) and the issue is exactly the same as here.
Looking at the migration you mentioned (m221203_000000_fix_empty_nav_sites.php), I can see why: you are inserting three columns into a table with other, required columns.

When I look at the navigation_navs_sites table I see there are also required columns dateCreated, dateUpdated and uid.
Running a manual query to do what the migration does also shows this issue:

```
insert into navigation_navs_sites(siteId, navId, enabled)
select s.id, n.id, 1
from sites s, navigation_navs n
```

leads to

```Error #1364 - Field 'dateCreated' doesn't have a default value```

**Comment by bgooren** [comment] 2023-01-05 18:37
Ok just to follow-up (@engram-design):

Browsing the source code it looks like the uid column is not used anywhere, so I decided to just copy the site value for now:

```
insert into navigation_navs_sites(siteId, navId, enabled, dateCreated, dateUpdated, uid)
select s.id, n.id, 1, now(), now(), s.uid
from sites s, navigation_navs n
```

After that I ran `./craft project-config/apply` again, which did not give any errors now.
Then I marked all failed queue items for retry, and ran `./craft queue/run`.
So far, everything works as expected.

Kind request to let me and others now if I should put any other value in `navigation_navs_sites.uid`.
And I guess this could be the root cause of upgrade issues.
Perhaps a check for errors when running a query in the future?

**Comment by engram-design** [comment] 2023-01-06 00:01
Good point, I forgot I wasn't dealing with records there (which include `dateCreated`, `dateUpdated` and `uid` automatically). Should be fixed in [2.0.16](https://github.com/verbb/navigation/releases/tag/2.0.16)

**Closed as completed by engram-design** 2023-01-06 00:01 UTC

**Comment by elfacht** [comment] 2023-01-26 11:29
Facing the same issue:

* Craft CMS 4.3.6.1  
* Navigation 2.0.16 

Only showing one set: 

![Screen shot 2023-01-26 um 12 28 04](https://user-images.githubusercontent.com/529443/214824868-42dbd7ae-dedb-4ef6-a016-c1cbc4dabec5.jpg)

But the DB says otherwise:
![Screen shot 2023-01-26 um 12 27 53](https://user-images.githubusercontent.com/529443/214824935-d28d9d49-906d-487e-b75d-0284694c6cdc.jpg)

The queries still work in the frontend, but accessing is not possible.

Somehow `navigation_navs_sites` shows the sets as disabled:

![Screen shot 2023-01-26 um 12 34 07](https://user-images.githubusercontent.com/529443/214825840-37250a66-d91f-428e-b5cc-8f1525f03a15.jpg)

**Comment by bgooren** [comment] 2023-01-26 12:08
> Facing the same issue:
> 
> * Craft CMS 4.3.6.1
> * Navigation 2.0.16
> 
> Only showing one set:
> 
> ![Screen shot 2023-01-26 um 12 28 04](https://user-images.githubusercontent.com/529443/214824868-42dbd7ae-dedb-4ef6-a016-c1cbc4dabec5.jpg)
> 
> But the DB says otherwise: ![Screen shot 2023-01-26 um 12 27 53](https://user-images.githubusercontent.com/529443/214824935-d28d9d49-906d-487e-b75d-0284694c6cdc.jpg)
> 
> The queries still work in the frontend, but accessing is not possible.
> 
> Somehow `navigation_navs_sites` shows the sets as disabled:
> 
> ![Screen shot 2023-01-26 um 12 34 07](https://user-images.githubusercontent.com/529443/214825840-37250a66-d91f-428e-b5cc-8f1525f03a15.jpg)

Hi! What was your previous version of the plugin? Perhaps you had the same issue I did: the database migrations were fixed in 2.0.16, but if you were already at a 2.x version they were already run. 2.0.16 does not include a new migration to fix broken installs. You can easily check if you are facing the same issue: missing rows in table `navigation_navs_sites`.

**Comment by elfacht** [comment] 2023-01-26 12:15
@bgooren The last update was from `2.0.13` to `2.0.16` and before that it was from `2.0.10` to `2.0.13`. I can't say with which update this problem occured exactly tbh.

**Comment by bgooren** [comment] 2023-01-26 12:17
> @bgooren The last update was from `2.0.13` to `2.0.16` and before that it was from `2.0.10` to `2.0.13`. I can't say with which update this problem occured exactly tbh.

Can you check your `navigation_navs_sites` table? it should have a row for each site + nav combination. See my two comments earlier in this issue.

**Comment by elfacht** [comment] 2023-01-26 12:47
@bgooren The rows are identical as seen in my screenshots. The first is from `navigation_navs` the second one from `navigation_navs_sites`. each table has 6 rows. I enabled the disabled entries by hand and they are appear now.

**Comment by bgooren** [comment] 2023-01-26 12:58
> @bgooren The rows are identical as seen in my screenshots. The first is from `navigation_navs` the second one from `navigation_navs_sites`. each table has 6 rows. I enabled the disabled entries by hand and they are appear now.

That sounds similar to https://github.com/verbb/navigation/issues/309

I think the solution in that case was simply to mark all rows as enabled yourself.

**Comment by elfacht** [comment] 2023-01-26 13:15
@bgooren Thanks, I thought so. We already did it on production DB, but this shouldn't be the solution for future issues. The backend dev was sweating a bit … :D

**Comment by bgooren** [comment] 2023-01-30 13:26
> @bgooren Thanks, I thought so. We already did it on production DB, but this shouldn't be the solution for future issues. The backend dev was sweating a bit … :D

Agreed - we had the same feeling (sweating a bit when all navs suddenly disappeared from the admin). But then I looked into it and contributed to this ticket to help the creator fix it :-)

**Comment by daltonrooney** [comment] 2023-01-31 21:22
So this bug bit me on a deploy to production as well. The production site must have been just the wrong combination of Craft CMS + Navigation where the migration had already been run and didn't run again when it needed to. What I didn't know was the best way to re-run a migration, here's what I did:

* In the database, find the migration row with the name `m221203_000000_fix_empty_nav_sites` and delete it. 
* From the command line, run `php craft migrate/all` and the migration should appear as pending. Run it.
* From the control panel, re-run the failed jobs in the queue.

That seems to have done the trick.

**Comment by Saboteur777** [comment] 2023-03-31 12:53
@daltonrooney Just ran into the same issue, but these steps solved the issue, thanks!

**Comment by joelstrom** [comment] 2023-11-09 14:35
I am facing the same issue where the navigations have disappeared from the admin, although they still exist in the database.
Running project-config/apply gives errors such as "error: The nav 'Footer Navigation' is not enabled for the site '1'", and trying to resave navigation nodes or rebuilding project config does not make a difference.

I have no row named m221203_000000_fix_empty_nav_sites (or anything with "nav") in the craft_migrations table.

Project got recently upgraded to newest Craft 3 (3.9.5) + plugin version (1.4.33), followed by Craft upgrade to 4.5.9 and 2.0.22 respectively.

Any suggestions on how to get the navigations to reappear in the admin?

**Comment by engram-design** [comment] 2023-11-10 01:36
If there's no Navigation migrations, it sounds like they haven't been run, which would be the cause for this error. You should see a few, such as:

<img width="692" alt="image" src="https://github.com/verbb/navigation/assets/1221575/364ab7cb-b36b-47f5-8bb8-58607fb089c9">

So there are **no** migrations where the `track` column is `plugin:navigation`?

There should be a `navigation_navs_sites` table, if you can confirm that? There should be a row in there for every navigation. It may be that you need to manually add those rows if they've not come across, but if you can confirm my previous questions first?

**Comment by joelstrom** [comment] 2023-11-10 08:54
Aha! Found 25 rows with `track` column being `plugin:navigation`.

I can also see the `navigation_navs_sites` table, but there is only 1 navigation there although we should have 4 in total.

**Comment by joelstrom** [comment] 2023-11-13 13:13
Any suggestion on how to get the migrations to run correctly?

**Comment by engram-design** [comment] 2023-11-13 21:56
I would say it'll be much quicker to just manually add the rows to the `navigation_navs_sites` table, which are pretty simple. All that you need to do is link the `navId` to a nav, and the `siteId` to every site on your install, and set `enabled` to `true`. Creating these rows manually via your favourite SQL client should be the quickest solution.

Otherwise, I would need a copy of your database _before_ your upgrade, to see what might have gone wrong. For similar issues where this has happened, I haven't been able to replicate the issue, even with the database in question - but if you're able to, happy to solve it "properly".

**Comment by joelstrom** [comment] 2023-11-14 08:55
Thanks, we will attempt the manual database update if necessary. 
For now it seems like the issue has disappeared by itself, as doing the migration / project config apply once more on a fresh database seemed to have gone through without any issues, even if no version updates had been done in between.
