### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by pseudoclass** [verbb/navigation#86] opened 2019-04-30 16:53 UTC
### Description

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dateDeleted' in 'where clause'
The SQL being executed was: SELECT *
FROM `navigation_navs`
WHERE `dateDeleted` IS NULL
ORDER BY `sortOrder`

Migration: verbb\navigation\migrations\m181110_000000_add_elementSiteId

Output:

    > add column elementSiteId integer AFTER `elementId` to table {{%navigation_nodes}} ... done (time: 0.137s)
    > create index navigation_nodes_elementSiteId_idx on {{%navigation_nodes}} (elementSiteId) ... done (time: 0.022s)
    > add foreign key navigation_nodes_elementSiteId_fk: {{%navigation_nodes}} (elementSiteId) references {{%sites}} (id) ... done (time: 0.029s)
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dateDeleted' in 'where clause'
The SQL being executed was: SELECT *
FROM `navigation_navs`
WHERE `dateDeleted` IS NULL
ORDER BY `sortOrder` (/Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT *\nFROM `...')
#1 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT *\nFROM `...')
#2 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /Users/michael/Sites/pbs-hub/vendor/verbb/navigation/src/services/Navs.php(56): yii\db\ActiveQuery->all()
#6 /Users/michael/Sites/pbs-hub/vendor/verbb/navigation/src/services/Navs.php(72): verbb\navigation\services\Navs->getAllNavs()
#7 /Users/michael/Sites/pbs-hub/vendor/verbb/navigation/src/elements/Node.php(265): verbb\navigation\services\Navs->getNavById('2')
#8 /Users/michael/Sites/pbs-hub/vendor/verbb/navigation/src/elements/Node.php(299): verbb\navigation\elements\Node->getNav()
#9 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/services/Elements.php(403): verbb\navigation\elements\Node->beforeSave(false)
#10 /Users/michael/Sites/pbs-hub/vendor/verbb/navigation/src/migrations/m181110_000000_add_elementSiteId.php(28): craft\services\Elements->saveElement(Object(verbb\navigation\elements\Node), true, false)
#11 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/db/Migration.php(56): verbb\navigation\migrations\m181110_000000_add_elementSiteId->safeUp()
#12 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#13 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(verbb\navigation\migrations\m181110_000000_add_elementSiteId))
#14 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#15 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#16 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#17 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#18 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#21 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#22 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#23 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#24 /Users/michael/Sites/pbs-hub/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#25 /Users/michael/Sites/pbs-hub/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /Users/michael/Sites/pbs-hub/web/index.php(21): yii\base\Application->run()
#27 {main}
```

### Steps to reproduce

1. Running composer update
2. After DB update the previous migration error is displayed

### Additional info

- Plugin version: Updating from 1.0.12 to 1.1.11
- Craft version: 3.1.23

**Comment by engram-design** [comment] 2019-05-01 14:57
What Craft version were you updating from? I couldn't reproduce this with just going from 1.0.12 to 1.1.11

**Comment by pseudoclass** [comment] 2019-05-03 12:44
Updated Craft from 3.0.33 -> 3.1.23

**Comment by engram-design** [comment] 2019-07-24 00:32
Fixed in the latest Craft versions.

**Closed as completed by engram-design** 2019-07-24 00:32 UTC
