### ISSUE TITLE
FR: Ability to choose a different element once node saved

### ISSUE THREAD

**Issue by billythekid** [verbb/navigation#35] opened 2018-09-20 11:27 UTC
This may already be on the radar.

As it stands we can't change the element chosen for a nav item once it's been set without deleting and adding the node as a new node. This is particularly annoying when it's a top level node with children.

The workaround for this is to save all nodes as custom/manual and manually change the URL should the element URL change. Not ideal.

This is to request that 'Choose Entry' etc be an available option in the node settings. (probably around where the link to the entry's cpEditUrl is)

**Comment by billythekid** [comment] 2018-09-20 11:28
If I get a chance I'll PR this but I'm not familiar with Garnish or the element pickers.

**Comment by engram-design** [comment] 2019-02-09 23:46
Closing as a duplicate of https://github.com/verbb/navigation/issues/52

**Closed by engram-design** 2019-02-09 23:46 UTC
Labels: feature request

**Comment by engram-design** [comment] 2020-01-08 13:49
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
